
#include <iostream>
    #include <fstream>

    int main() {
        std::ofstream out("output.txt", std::ios::out);
        if (!out) {
            std::cerr << "Error: Could not open output.txt" << std::endl;
            return 1;
        }
        out << "Hello from CI/CD! This file was generated by the app.";

        out.close();
        std::cout << "Successfully wrote to output.txt";

        return 0;
    }